### ISSUE TITLE
Deprecate "b_zone_id" and "b_city_id"

### ISSUE THREAD

**Issue by tianxie1995** [SEMCOG/semcog_urbansim#35]
"b_zone_id" and "b_city_id" were created to deal with super parcels in the 2045 forecast. 

In the 2050 forecast, data has well-nested geographies without this issue

**Comment by semcogli** [comment]
b_city_id and b_zone_id were updated to city_id and zone_id in refiner_events table. New hdf is on test_inputs folder. You can drop remaining b_zone_id and b_city_id now.

**Comment by tianxie1995** [comment]
> b_city_id and b_zone_id were updated to city_id and zone_id in refiner_events table. New hdf is on test_inputs folder. You can drop remaining b_zone_id and b_city_id now.

There are some `b_city_id` in `agent_expression`. I have replaced them with `city_id` in `/RDF2050/model_inputs/test_inputs/all_semcog_data_02-02-18-final-forecast_newbid.h5`.

**Comment by semcogli** [comment]
I updated those on my local but Looks like the copied one was still not correct.

**Comment by semcogli** [comment]
In addition, another place we need to look into is the "output_indicators.py". It uses "b_" geographies quite extensively.

**Comment by tianxie1995** [comment]
> I updated those on my local but Looks like the copied one was still not correct.

Should be there now, I think the copying takes a bit of time. 

> In addition, another place we need to look into is the "output_indicators.py". It uses "b_" geographies quite extensively.

Yes, I saw those. I can start cleaning this up after getting the test output.
